dheeraj-2000/dsalgo

- Linked_List/detect cycle in Linkedlist
> detect cycle in Linkedlist

- Linked_List/MiddleNodeLinkedlist.cpp
program to find the middle node of a singly linked list.
> MiddleNodeLinkedList

- Leetcode problems/longest_common_prefix.cpp
> Added Longest Common Prefix

- Sort/Insertion sort.cpp
- Sort/Selection sort.cpp
- Sort/bubble sort.cpp
- Sort/heap sort.cpp
- Sort/merge sort.cpp
- Sort/quicksort.cpp
I have added 6 most common sorting algorithms. Kindly have a look
> sorting algorithms in c++ language

- Leetcode problems/string permutation.java
Given a string str , we are finding the all the permutations of str in java
#1
> Permutation of String in  Recursive way

- DP/Recursive-Function/Recursive function.cpp
- DP/Rod-Cutting/Rod-cutting_top-down_bottom-up.cpp
> rod cutting

- CodeForces Problems/CF-1408-A-Circle Coloring.cpp
- CodeForces Problems/CF-635-B-Ichihime and Triangle.cpp
- CodeForces Problems/cf634_B.cpp
- CodeForces Problems/cf_633.cpp
- CodeForces Problems/cf_634_B.cpp
- CodeForces Problems/cf_636_A.cpp
- CodeForces Problems/cfdiv21605.cpp
- CodeForces Problems/cfdiv4.cpp
- CodeForces Problems/cfround636B.cpp
- CodeForces Problems/cfwatermelon.cpp
- CodeForces Problems/codeforces635_B.cpp
- cpp_template.cpp
- trash_codes/kth_element.cpp
- trash_codes/large_response_postman.cpp
- trash_codes/remove_element.py
Added a c++ template which is very useful for competitive programming. The template contains many useful functions.
also i formatted the code for some of the files so that people could understand it better.
> added a cpp template and formatted the code

- Binary_Search_Tree/Least_common_Anccestor_in_BST.cpp
- Binary_Search_Tree/construct_BST_from_postOrder.cpp
- Binary_Search_Tree/hight_of_BST.cpp
- Binary_Search_Tree/level_order_travesal.cpp
- Binary_Search_Tree/min_ele_inBST.cpp
- Binary_Search_Tree/normal_BST_to_balanceBST.cpp
- Binary_Search_Tree/sum_of_leaf_nodes_inBST.cpp
I have added level order travesal, searching, recunstruction of BST, sum of leaf nodes, min value in BST, construction of BST from postorder.
> added various implementation of BST

- README.md
Plz merge my pull request, it is part of Hactoberfest2020.
> Added to Link List

- Leetcode problems/arrangeCoins.py
- Leetcode problems/prisoncellsndays.py
- Leetcode problems/reversebinarytreelevel.py
> Leet Code More Problems

- Graph/Dijkstras Algorithm/Python/Dijkstras Algo.py
- Graph/Floyd Warshall Algorithm/Floyd Warshall Algorithm.py
- Graph/Prim's Minimum Spanning Trees/Prim's MST.py
- Graph/Strongly Connected Graphs/Strongly Connected Graphs.py
Pull Request For HacktoberFest 2020.
Added Prim's MST Algo for Python.
> Prim's MST

- DP/EGG Dropping Puzzle/ProblemSatement.txt
- DP/EGG Dropping Puzzle/solution.c
- DP/EGG Dropping Puzzle/solution.cpp
- DP/EGG Dropping Puzzle/solution.java
- DP/EGG Dropping Puzzle/solution.py
I have added Egg droping Problem of DP with problem statement and it's solution in 4 languages.
> Added Egg Dropping Problem Of DP

- Graph/Dijkstras Algorithm/Python/Dijkstras Algo.py
Pull Request For HacktoberFest 2020.
Added Dijkstras Algorithm for python language.
> dijkstras algo

- Graph/Dijkstras Algorithm/Python/Dijkstras Algo.py
- Graph/Strongly Connected Graphs/Strongly Connected Graphs.py
Pull Request For HacktoberFest 2020.
Added Strongly Connected Graphs Algorithm in Python.
> Strongly Connected Graphs

- Graph/Dijkstras Algorithm/Python/Dijkstras Algo.py
- Graph/Floyd Warshall Algorithm/Floyd Warshall Algorithm.py
- Graph/Strongly Connected Graphs/Strongly Connected Graphs.py
Pull Request For HacktoberFest 2020.
Added the Floyd-Marshall Algorithm in Python.
> Floyd-Marshall Aglorithm(DP)

- Sort/BucketSort.cpp
- Sort/CountingSort.cpp
- Sort/RadixSort.cpp
Added Radix Sort, Bucket Sort, and Counting Sort in C++ language.
> Added linear time sorts

- DP/word break.cpp
Given a string and dictionary of words, determine if string can be segmented into a space separated sequence of more or more dictionary words
example - 
dict[] = { "this", "th", "is", "famous", "Word", "break", "b",
        "r", "e", "a", "k", "br", "bre", "brea", "ak", "problem" };
string = "Wordbreakproblem"
#14
> word break problem in dp

- DP/edit distance.py
The levinshtein distance between two words is the minimum number of single character edits (that is insertions, deletions or substitution ) required to transform one string to another
for ex the levinshtein distance between kitten and sitting is 3
kitten->sitten (substitution of s for k)
sitten->sittin (substitution of i for e)
sittin -> sitting (insertion of g at end)
#14
> The levinshtein distance problem

- Arrays/bookAllocation.cpp
Book Allocation problem for technical interview
> Add file via upload

- Algorithms/Math/BinaryExponentiation.cpp
- Algorithms/Math/SieveOfEratosthenes.cpp
Added,
1. Binary Exponentiation
2. Sieve of Eratosthenes
> Added two math algorithms

- Algorithms/Math/AckermannFunction.cpp
- Algorithms/Math/CatalanNumbers.cpp
- Algorithms/Math/FermatsLittleTheorem.cpp
Added,
1. Ackermann Function
2. Catalan Numbers
3. Fermat's Little Theorem
> Added 3 math algorithms

- Binary_tree/InvertBinaryTree.cpp
Added algorithm to invert binary tree iteratively and recursively in C++.
#1
> Added algorithm to invert binary tree

- Searching algos/Binary_Search.cpp
- Searching algos/Fibonacci_Search.c
- Searching algos/Interpolation_Search.cpp
- Searching algos/Jump_Search.cpp
- Searching algos/Linear_Search.cpp
The codes of 5 searching algorithms have been contributed by me to this repo.
> 5 Searching algos added

- Arrays/stacks_implementation.cpp
Issue: #1 
The Implementation of Stacks data structure in CPP is added. As it is implemented is arrays so it is placed in the arrays directory.
> Stacks Implementation added

- Linked_List/insert_Circular linked  list.c
@dheeraj-2000 Hey I have added insert in the circular linked list please check it and merge
> Circular Linked List

- DP/Minimum_Coin_Change/minCoinChange.py
For Issue: Add Famous DP problems #14. The problem can be found here: https://www.codesdope.com/course/algorithms-coin-change/.
> Added Minimum Coin Change problem to the DP folder. Language is Python 3

- Sort/dnf-sort.cpp
Respected Sir, 
With due respect, I want to mention that I added a dnf-sort.cpp file that has code for dnf-sort, It is very helpful in cases where 3 numbers input stream is provided it is very fast and light weight but is missing from your Sort folder code.
> Added dnf-sort by GamerNishant

- Searching algos/Binary-Search.py
- Searching algos/Linear_Search.py
- Sort/Bubble_Sort.py
It is a Linear Searching Algorithm program written using Python programming language.
> Linear Search Program using Python

- Sort/InsertionSort.py
- Sort/SelectionSort.py
SelectionSort.py with function execution time added.
> Sort - SelectionSort.py, InsertionSort.py

- Algorithms/Math/NewtonsMethod.cpp
This commit adds Newton's Method and nth root calculation.
> Add Newton's Method math algorithm

- Recursion/Flood_fill_algorithm.cpp
Hello!
I added the _Flood-fill algorithm_ implemented in C++ in a new folder named _Recursion_. The flood fill algorithm works in a way similar to the bucket tool in MS Paint. This Is also a really famous interview problem. I hope this is a decent addition to your repository.
Thanks!
> Added Flood fill algorithm in C++

- Trees/Level Order Traversal.cpp
The written code is well commented on. Easy to Understand.
> Added Level order traversal of tree

- Algorithms/Math/RSA.cpp
Implemented the RSA encryption and decryption algorithm in c++
> Added RSA encryption and decryption algorithm

- Sort/QuickSort.py
Hello. I wrote quicksort code on python, and Add some explainations.
> Add quicksort algorithm on python #17

- Binary_tree/vertical_traversal.cpp
vertical order traversal of binary tree in cpp code
> vertical order traversal of binary tree in cpp code

- DP/Fibincci_series/Fibonacci.java
Displays the Fibonacci sequence up to a certain number using recursion and memoization in Java
> Added Fibonacci sequence using memoization

- Leetcode problems/3. Longest Substring Without Repeating Characters/LongestSubString.cpp
- Leetcode problems/3. Longest Substring Without Repeating Characters/README.md
- Leetcode problems/GenerateParanthesis.cpp
Added link to the  above problem
> Generate paranthesis

- contests/codechef/oct20long/Add square.cpp
- contests/codechef/oct20long/D-Dimensional MST
Solution for D-MST asked in  Codechef October long challenge.
> Create D-Dimensional MST

- Algorithms/Graph/tarjan's algorithm.cpp
C++ implementation of Tarjan’s Algorithm to find Strongly Connected Components in a graph.
> Create tarjan's algorithm.cpp

- Leetcode problems/search-in-2d-matrix.cpp
search in 2d matrix leetcode medium question in c++ code
> search in 2d matrix leetcode medium

- Leetcode problems/set-matrix-zeroes-leetcode.cpp
added leetcode problem set matrix zeroes
> added leetcode problem set matrix zeroes

- Interview_Questions/delete_middle.cpp
- Stack/delete_middle.cpp
interview question: delete middle of stack without using additional data structure
> delete middle of stack

- Binary_tree/bottom_view.cpp
- Binary_tree/boundary_traversal.cpp
- DP/Equal_Sum_partition/equal_sum_parititon_memoization.cpp
- DP/Equal_Sum_partition/equal_sum_partition_Recursive.cpp
- DP/Equal_Sum_partition/equal_sum_partition_bottom-up.cpp
- Leetcode problems/Set_matrix_zeros.cpp
added Equal sum partition Problem code for DP
using Recursion, Memoization and tabulation method.
> added equal_sum_partition_dp_code in c++

- Trees/Boundary_Traversal_of_Binary_Tree.cpp
Hey, I've added the code for Boundary Traversal of a Binary Tree in C++ along with a well-formatted Problem Statement, Example, Approach and the functions required for code. Do let me know if any changes are required.
Thank you in advance :)
> Boundary Traversal of Binary Tree added.

- Set operations/cartesian.c
- Set operations/differenceset.c
- Set operations/intersection.c
- Set operations/powerset.c
- Set operations/symmetricdiff.c
- Set operations/union.c
Set operations added and can be implemented using c .
> Set operation added

- DP/edit distance.cpp
Issue #14 
The current Edit Distance solution present in the repository is written in python and follows a recursive approach.
Adding a C++ version that uses a 2D matrix instead.
> Add C++ solution for DP Edit Distance problem

- CodeForces Problems/CF_677_F.cpp
- CodeForces Problems/cf_644_div3_H.cpp
- CodeForces Problems/cf_educational_97_C.cpp
DP Approach to solve the problem
> Codeforces Round 677 Div 3 F Solution Added

- DP/primitive_calculator.cpp
problem :- You are given a primitive calculator that can perform the following three operations with
the current number x: multiply x by 2, multiply x by 3, or add 1 to x. Your goal is given a
positive integer n, find the minimum number of operations needed to obtain the number n
starting from the number 1.
solution description: implemented in c++ using Dynamic programming
> added_primitive_calculator.cpp

- Algorithms/TSP Genetic.cpp
Implementation of Travelling Salesman Problem using Genetic Algorithm in C++.
> Create TSP Genetic.cpp

- CodeForces Problems/Codeforces_667_Div3/A.cpp
- CodeForces Problems/Codeforces_667_Div3/B.cpp
Hello!
I have added the solutions to the A and B problems of the Codeforces Round 667 Div 3 Contest. Hope this helps.
Thanks!
> Added Codeforces Div 3 Round 667 Solutions

- CodeForces Problems/CF-1385-B-Div_3-Restore the Permutation by Merger.cpp
- CodeForces Problems/CF-1399-A-Div_3-Remove Smallest.cpp
Added Div-3 1399-A Codeforces contest Solution of program Remove Smallest in C++.
> Added Remove Smallest Codeforces Solution

- DP/Subset-sum/DP table for example.txt
- DP/Subset-sum/Problem_statement.txt
- DP/Subset-sum/Solution.cpp
- Add Problem statement
- Add solution.cpp
- Add DP table
Soved issue (#14)
> Add Subset-Sum problem

- Searching algos/Interpolation_Search.py
Uploaded an Interpolation Search algorithm program written using Python Programming language into the folder Searching Algos.
> Added Interpolation Search Algorithm using Python

- Trees/minimum depth of binary tree.cpp
Recursion based solution with visualisation to find minimum depth of binary tree
> Create minimum depth of binary tree.cpp

- SimpleLinkedList/linkedList.c
- SimpleLinkedList/linkedList.h
- SimpleLinkedList/linkedListTest.c
Simple unidirectional linked list in C with example.
What i have done 🤔: 
> - createList;
> - add;
> - printList;
> - isEmpty;
> - removeBack;
> - size;
> Simple unidirectional linked list in C

- Arrays/transpose_array.cpp
This program calculated transpose of matrix (multidimensional array) implemented using c++ language.
> added program for transpose of matrix

- DP/Kadane-Algorithm/Largest-Sum-Contiguous-Subarray.cpp
Added Kadane's Algorithm to find maximum contigious sub-array sum.
> Added Kadane

- Arrays/Organising_Containers.c
This problem develops your basic concepts about rows & columns of multidimensional arrays, how are they organised.
Good use of variable flag indicator. Learn the Use of break statement, nested if else loops.  [HackerRank Profile](https://www.hackerrank.com/Achal_2702)
Happy Coding!
Keep Learning!
> Added Soln. of Orgainising Containers of Balls Problem

- Algorithms/Math/double_factorial.cpp
double factorial  of a number n (denoted by n!!) is the product of all the integers from 1 up to n that have the same parity(odd or even) as n. This can be done  in O(n) time complexity and O(1) space complexity
> Double factorial in c++ language

- Linked_List/Reverse a Linked List in groups
Reverse a Linked List in groups
> Reverse a Linked List in groups

- Leetcode problems/word_break.cpp
> Added Word Break Problem

- Leetcode problems/house_robber.cpp
> Added House Robber Problem

- Leetcode problems/factorial_trailing_zeroes.cpp
##Leetcode Problem No. 172
##Description
Given an integer n, return the number of trailing zeroes in n!
Fixes #1
> Added Factorial Trailing Zeroes Problem

- Sort/CycleSort.cpp
#17 
Hi @dheeraj-2000, I have added the Cycle Sort algorithm and its implementation in C++ in the sort folder. Please review this.
> Added Cycle Sort Algorithm

- Hashing/DoubleHashingC++.cpp
- Hashing/Hash Table Class Chaining.cpp
- Hashing/Hash Table Quadratic Probing.cpp
- Hashing/HashTableLinearProbingC++.cpp
this includes Hashing using Double Hashing, Hash Table Class Chaining, Hash Table Quadratic Probing, Hash Table Linear Probing.
> Hashing techniques

- Linked_List/LinkedListReversePartial.cpp
Hi! Greetings of the day!!
I have added a program in C language that continuously reverses n nodes of a Linked list after skipping m nodes of the same linked list until end of the linked list is encountered. There is a popular problem on GeeksForGeeks that asks us to continuously delete few nodes after skipping few nodes. This program is inspired from that idea but here we reverse the nodes instead of deleting them.
> added a C code that partially reverses a linked list

- Arrays/Union.c++
@dheeraj-2000 Hey I added union of set check it and merge it
> Union of set

- Arrays/Intersection.c++
@dheeraj-2000 Hey I have added the Intersection of the set please check it and merge it
> Intersection of set

- Linked_List/delete in CLL.c
@dheeraj-2000 Hey I have added delete operation in the circular linked list please check it and merge
> Circular Linked list delete operation

- Trees/AVL_TREE.cpp
> AVL_TREE.cpp

- Graph/Krushals Min Cost Spanning Tree.cpp
Krushals Min Cost Spanning Tree
> Krushals Min Cost Spanning Tree.cpp

- DP/Binomialcoefficient/binomial.cpp
- DP/Binomialcoefficient/binomial1.cpp
- DP/Binomialcoefficient/binomial2.cpp
- DP/Binomialcoefficient/binomial3.cpp
- DP/Binomialcoefficient/binomial4.cpp
- DP/Binomialcoefficient/binomial5.cpp
- DP/coin change problem/coinchange.cpp
- DP/coin change problem/coinchange1.cpp
- DP/coin change problem/coinchange2.cpp
Hey! I added some program in dp section. please merge those programs.
Thank you in advance.
> added some program in dp section

- Leetcode problems/PartitionToKEqualSumSubsets.cpp
I have added a backtracking based solution to the leetcode problem - Partition to K equal sum subsets. Also mentioned the time complexity.
> Added the problem - Partition to K equal sum subsets

- Arrays/catalan_numbers.cpp
C++ program to find the nth Catalan Number
> Created catalan_numbers.cpp

- Leetcode problems/LongestConsecutiveSequence.cpp
Please review @dheeraj-2000 . 
I made a new PR, incase you would not want to add implementation details of Union Find in your repo.
> Problem number 128 : Longest Consecutive Sequence Leetcode

- Sort/Heap_Sort.py
Added heap sort algorithm, written in python, in sort folder
> Added heap sort algorithm in python

- Binary_tree/find_LCA_binary_tress.cpp
CPP code to find the lowest common ancestor of two nodes in a binary tree
> Created find_LCA_binary_tress.cpp

- DP/Shortest Common Supersequence/problemStatement.txt
- DP/Shortest Common Supersequence/shortestCommonSuperSequence.cpp
Added a Dynamic programming problem - Shortest Commom Supersequence. Added the problem statement along with its optimal solution and time and space complexities.
> [ADD] shortest common supersequence

- Algorithms/Math/exponentiation_ii_2_cses_calculate_a^b^c.cpp
Explanation of how to solve a ^ (b^c) % M
> Created exponentiation_ii_2_cses_calculate_a^b^c.cpp

- DP/Gold_Mine_Problem_Cpp/gold_mine.cpp
- Sort/pigeonholeSort.cpp
Added Pigeon hole sort using C++
> Pigeonhole Sort in C++ & Gold mine DP

- DP/Pots_of_Gold_Game.cpp
> solution is added

- Stack/python/balanced_parenthesis.py
added balanced parenthesis code using stack in python
> balanced parenthesis in python

- Recursion/number of dice roll with target sum.cpp
> number of dice roll with target sum.cpp

- Algorithms/Detecting a cycle in a graph (Using three color mechanism).cpp
Detecting a cycle in a graph (Using three color mechanism)
> Hacktoberfest 2022

- Binary_Search_Tree/binarytree.c
This is a C program for Binary Search Tree
> Added C program

- CODECHEF EASY/ALTER.cpp
Instead of using logical or || operator in the if statement in 22 we can use the abs(), absolute value function to calculate the difference of x and y.
cstdlib library will be required
> Using abs function instead of logical OR in (22)

- Sort/Heap_Sort.java
> Added Heap_Sort.java

- Leetcode problems/69.RotateList.cpp
Added Program for issuse #489 Rotate List.
Please Accept my PR.
> Added RotateList Program

- README.md
I have added your name as the credit below, do check it out!!
> I got uh bruh! added your credit name at footer as your legacy

- Leetcode problems/single_number.py
Leet Code Problem 136 Single Number Problem #Hacktoberfest-2022
61 / 61 test cases passed
Status: Accepted
Runtime: 245 ms
Memory Usage: 15.7 MB
@dheeraj-2000
> 136 LeetCode single number problem python #Hacktoberfest

- Searching algos/binarySearch.java
Binary Search Algorithm in java
> added binary search algorithm in java

- Arrays/max_subarray_sum.js
Added a file to get the maximum continuous subarray sum in JS format
> max_subarray_sum in js format

- Algorithms/gcdEucidAlgo.cpp
- Leetcode problems/rotate2darray.cpp
- Leetcode problems/search_in2darray-II.cpp
Added cpp code -
1.Euclid Algorithm
2. Binary search in 2d array
3. Rotate 2d array by 90deg 
Please label the issue as hacktoberfest.
> Added 3 cpp code files

- Algorithms/variable/ChangesVariable.kt
i added variable changes not temp.
> abdul karim dsalgo

- Algorithms/quick_sort.py
Quick sort algorithm implementation in python.
> Added quick_sort.py  algorithm file 

- array/ArrayTraversal.c
reduced the number of for loops in code, increased the readibility of code by adding commetns and formatting the code.
> Optimised code readability.

- Algorithms/linearreg.py
- Algorithms/multiplereg.py
Simple linear regression is an approach for predicting a response using a single feature.
> regression.py

- Leetcode problems/LongestIncreasingSubseq.java
Contributing a  [Longest Increasing Subsequence](https://leetcode.com/problems/longest-increasing-subsequence/) leet code problem (medium difficulty) java code with necessary comments.
> Create LongestIncreasingSubseq.java Leetcode

- Algorithms/Strassensalgo.c
Added code for Strassen's algorithm in C
> Strassens algorithm in C

- Leetcode problems/Decode Ways.cpp
> Added Leetcode Problem Decode Ways in CPP

- CodeForces Problems/DoNotBeDistracted.java
Added solution to CodeForces problem #719-A in JAVA. The solution has a runtime of 140ms and is Accepted on CodeForces.
> #575 . Added solution to CodeForces problem #719-A in JAVA.

- CodeForces Problems/sort_0_1_2.cpp
Hello Sir,
I am Raman Kumar Gupta , with GitHub Id - Ramank2002
I contributed to your repository by adding a solution of sorting an array of 0s , 1s and 2s .
Kindly consider it and I'll be grateful to you.
Regards,
Raman Kumar Gupta
> I want to add solution of Sort 0s , 1s and 2s in an array on codestudio

- Leetcode problems/My _Calendar_III.cpp
solved my calendar problem of leetcode daily challenges
> Create My _Calendar_III.cpp

- DP/Minimum_Multiplications_to_Reach_End.cpp
Standard DP Problem asked in FIS global and DBS-DTI interview
> Minimum_Multiplications_to_Reach_End.cpp

- DP/Maximum_Score_From_performing_Multiplication.java
Added java code for the problem 'Maximum Score from Performing Multiplication Operations' mentioned in description of the file with examples. It is a DP problem , so added inside the DP folder. Please accept my PR.
> Added code for Maximum Score from Performing Multiplication Operations

- array/Euclid's Algo
hacktoberfest 2022 contribution
this is one of my first good first issue! :)
> Euclid's Algorithm 

- bitwiseOperators/swap_ith_and_jth_bit_position.py
Small program to swap bits using python with an example
> Add swapping of the ith and jth bit in a digit

- Leetcode problems/58Length-of-Last-Word.py
- bitwiseOperators/swap_ith_and_jth_bit_position.py
Python solution that doesn't require an extra object
> Leetcode problems

- Leetcode problems/403.FrogJump.cpp
- Leetcode problems/416.PartitionEqualSubsetSum.cpp
- Leetcode problems/583.DeleteOperationForTwoStrings.cpp
I have added leetcode solutions which are of medium and hard difficulty. I have tested all of the code and it is passing all the test cases efficiently.
> added leetcode solutions
